export type RoyalPerson = {
  id: string;
  kind: "royal";
  name: string;
  reading: string;
  title: "尊" | "皇子" | "親王" | "王";
  parent: string;
  lane: number;
  row: number;
  connection: string;
  note: string;
  sourcePage: 1 | 2;
};

// 宮内庁「天皇系図」1〜2頁に、歴代天皇の親子関係をつなぐ人物として
// 明記された皇子・親王・王などを収録。座標は既存の縦方向の時系列に
// 合わせつつ、天皇ノードと重ならないよう横方向へ分岐させている。
export const ROYAL_PEOPLE: RoyalPerson[] = [
  {
    id: "royal-yamato-takeru",
    kind: "royal",
    name: "日本武尊",
    reading: "やまとたけるのみこと",
    title: "尊",
    parent: "12",
    lane: -2.7,
    row: 13.05,
    connection: "景行天皇 → 仲哀天皇",
    note: "景行天皇の皇子で、仲哀天皇の父。宮内庁「天皇系図」で両天皇をつなぐ人物として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-iwasaka",
    kind: "royal",
    name: "磐坂市辺押磐皇子",
    reading: "いわさかのいちのべのおしは",
    title: "皇子",
    parent: "17",
    lane: 2.9,
    row: 20.5,
    connection: "履中天皇 → 顕宗・仁賢天皇",
    note: "履中天皇の皇子で、顕宗天皇・仁賢天皇の父として系図に記載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-wakanu",
    kind: "royal",
    name: "稚野毛二派皇子",
    reading: "わかぬけふたまた",
    title: "皇子",
    parent: "15",
    lane: -3.7,
    row: 17.2,
    connection: "応神天皇 → 継体天皇へ至る支系",
    note: "応神天皇の皇子。継体天皇へ至る五世の系譜の起点として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-ohodo",
    kind: "royal",
    name: "意富富杼王",
    reading: "おおほど",
    title: "王",
    parent: "royal-wakanu",
    lane: -3.9,
    row: 19.2,
    connection: "稚野毛二派皇子 → 乎非王",
    note: "稚野毛二派皇子から継体天皇へ至る支系をつなぐ王として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-ohi",
    kind: "royal",
    name: "乎非王",
    reading: "おひ",
    title: "王",
    parent: "royal-ohodo",
    lane: -3.9,
    row: 21.25,
    connection: "意富富杼王 → 彦主人王",
    note: "意富富杼王と彦主人王の間をつなぐ王として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-hikoushi",
    kind: "royal",
    name: "彦主人王",
    reading: "ひこうし",
    title: "王",
    parent: "royal-ohi",
    lane: -3.8,
    row: 23.4,
    connection: "乎非王 → 継体天皇",
    note: "乎非王の王子で、継体天皇の父として系図に掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-osaka",
    kind: "royal",
    name: "押坂彦人大兄皇子",
    reading: "おしさかのひこひとのおおえ",
    title: "皇子",
    parent: "30",
    lane: 3,
    row: 31.75,
    connection: "敏達天皇 → 舒明天皇・茅渟王",
    note: "敏達天皇の皇子で、舒明天皇と茅渟王の父として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-chinu",
    kind: "royal",
    name: "茅渟王",
    reading: "ちぬ",
    title: "王",
    parent: "royal-osaka",
    lane: -2.35,
    row: 33.55,
    connection: "押坂彦人大兄皇子 → 皇極・斉明・孝徳天皇",
    note: "押坂彦人大兄皇子の王子で、皇極（斉明）天皇・孝徳天皇の父として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-kusakabe",
    kind: "royal",
    name: "草壁皇子",
    reading: "くさかべ",
    title: "皇子",
    parent: "40",
    lane: -2.35,
    row: 41.35,
    connection: "天武天皇 → 文武・元正天皇",
    note: "天武天皇の皇子。元明天皇との間に文武天皇・元正天皇が生まれた系譜として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-toneri",
    kind: "royal",
    name: "舎人親王",
    reading: "とねり",
    title: "親王",
    parent: "40",
    lane: -3.7,
    row: 43.8,
    connection: "天武天皇 → 淳仁天皇",
    note: "天武天皇の皇子で、淳仁天皇の父として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-shiki",
    kind: "royal",
    name: "施基親王",
    reading: "しき",
    title: "親王",
    parent: "38",
    lane: 3.2,
    row: 43.8,
    connection: "天智天皇 → 光仁天皇",
    note: "天智天皇の皇子で、光仁天皇の父として掲載されています。",
    sourcePage: 1,
  },
  {
    id: "royal-morisada",
    kind: "royal",
    name: "守貞親王",
    reading: "もりさだ",
    title: "親王",
    parent: "80",
    lane: 8.25,
    row: 83.1,
    connection: "高倉天皇 → 後堀河天皇",
    note: "高倉天皇の皇子で、後堀河天皇の父として掲載されています。",
    sourcePage: 2,
  },
  {
    id: "royal-yoshihito",
    kind: "royal",
    name: "栄仁親王",
    reading: "よしひと",
    title: "親王",
    parent: "n3",
    lane: 1.05,
    row: 99.2,
    connection: "崇光天皇 → 貞成親王",
    note: "北朝第3代・崇光天皇の皇子。伏見宮の祖で、貞成親王の父として掲載されています。",
    sourcePage: 2,
  },
  {
    id: "royal-sadafusa",
    kind: "royal",
    name: "貞成親王",
    reading: "さだふさ",
    title: "親王",
    parent: "royal-yoshihito",
    lane: 1.45,
    row: 100.55,
    connection: "栄仁親王 → 後花園天皇",
    note: "栄仁親王の皇子で、第102代・後花園天皇の父。旧11宮家ともつながる共通祖先です。",
    sourcePage: 2,
  },
  {
    id: "royal-sanehito",
    kind: "royal",
    name: "誠仁親王",
    reading: "さねひと",
    title: "親王",
    parent: "106",
    lane: 4.9,
    row: 106.5,
    connection: "正親町天皇 → 後陽成天皇",
    note: "正親町天皇の皇子で、後陽成天皇の父として掲載されています。",
    sourcePage: 2,
  },
  {
    id: "royal-naohito",
    kind: "royal",
    name: "直仁親王",
    reading: "なおひと",
    title: "親王",
    parent: "113",
    lane: 7.7,
    row: 114.45,
    connection: "東山天皇 → 典仁親王",
    note: "東山天皇の皇子。閑院宮の祖で、典仁親王の父として掲載されています。",
    sourcePage: 2,
  },
  {
    id: "royal-sukehito",
    kind: "royal",
    name: "典仁親王",
    reading: "すけひと",
    title: "親王",
    parent: "royal-naohito",
    lane: 7.7,
    row: 116.75,
    connection: "直仁親王 → 光格天皇",
    note: "直仁親王の皇子で、光格天皇の父として掲載されています。",
    sourcePage: 2,
  },
];
